---
language: php

php: 7.2

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini

before_install:
  # Composer
  - export COMPOSER_MEMORY_LIMIT=-1
  - travis_retry composer self-update
  - composer global require hirak/prestissimo
  - composer config repositories.openideal git https://github.com/nvelychenko/openideal.git

  # Make
  - git clone --branch 3.x-dev https://github.com/nvelychenko/openideal-composer.git openideal-composer
  - cd openideal-composer
  - mkdir -p web/sites/default/files
  - chmod -R 777 web/sites/
  - make up
  - composer --verbose validate
  - travis_retry composer install

install:
  - make install

script:
  - vendor/bin/phpcs web/profiles/ --standard=Drupal,DrupalPractice --ignore="*.js,*.css,*.scss,*.sass,*.less,node_modules" --extensions=php,module,inc,install,test,profile,theme,info,yml
