---
language: php

php: 7.2

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini

before_install:
  - export COMPOSER_MEMORY_LIMIT=-1
  - composer global require hirak/prestissimo
  # Make
  - apt-get update > /dev/null
  - apt-get install make
  - git clone https://github.com/nvelychenko/openideal-composer.git openideal-composer
  - cd openideal-composer
  - composer install
  - make up

install:
  - make install
  - vendor/bin/phpcs web/profiles/ --standard=Drupal,DrupalPractice --ignore="*.js,*.css,*.scss,*.sass,*.less,node_modules" --extensions=php,module,inc,install,test,profile,theme,info,yml